import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Akshar } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

const akshar = Akshar({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-akshar',
    weight: '700'
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    searchParams,
}: {
    children: React.ReactNode;
    searchParams?: SearchParamProps;
}) {
    const params = searchParams || {};
    return (
        <html lang="en" className="h-full">
            <body className={akshar.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
